name: Backend CI Pipeline

on:
  push:
    branches:
      - main  
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main  
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Node.js 20.9
        uses: actions/setup-node@v3
        with:
          node-version: 20.9

      - name: Install dependencies
        working-directory: ./backend
        run: npm install
        

      - name: Run Linting
        working-directory: ./backend
        run: npm run lint
        
      - name: Run Tests
        working-directory: ./backend
        run: npm run test
        env:
          MONGODB_URI_PROD: ${{secrets.MONGODB_URI_PROD}} 
          MONGODB_URI_DEV: ${{secrets.MONGODB_URI_DEV}}
          MONGODB_URI_TEST: ${{secrets.MONGODB_URI_TEST}} 
          PORT: ${{secrets.BACKEND_PORT}}
          ORIGIN: ${{secrets.ORIGIN}}

      - name: Build the project
        working-directory: ./backend
        run: node api/index.js
        env:
          NODE_ENV: development
          MONGODB_URI_PROD: ${{secrets.MONGODB_URI_PROD}} 
          MONGODB_URI_TEST: ${{secrets.MONGODB_URI_TEST}} 
          MONGODB_URI_DEV: ${{secrets.MONGODB_URI_DEV}}
          PORT: ${{secrets.BACKEND_PORT}}
          ORIGIN: ${{secrets.ORIGIN}}
