name: CI Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Node.js 20.9
        uses: actions/setup-node@v3
        with:
          node-version: 20.9

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      # - name: Run Linting
        # working-directory: ./backend
      #   run: npm run lint

      # - name: Run Tests
        # working-directory: ./backend
      #   run: npm run test

      - name: Build the project
        working-directory: ./backend
        run: node api/index.js